Release v1.70.1

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,7 +4,7 @@ executors:
   bloxroute-executor:
     docker:
     # TODO: Use AWS repository or create bloXroute account on Docker Hub
-    - image: circleci/python:3.7
+    - image: circleci/python:3.8
     environment:
       PYTHONPATH: /home/circleci/ws/bxcommon/src:/home/circleci/ws/bxgateway/src:/home/circleci/ws/bxextensions:/home/circleci/ws/bxcommon-internal/src/
     working_directory: ~/ws
@@ -19,13 +19,27 @@ jobs:
       - checkout:
           path:
             "bxgateway"
-      - restore_cache: # restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run
-          key: bx-{{ .Branch }}-{{ checksum "bxgateway/requirements.txt" }}-{{ checksum "bxgateway/requirements-dev.txt"}}
+      - run: # install and activate virtual environment with pip
+          command: |
+            cd ~/ws
+            python -m virtualenv venv
+      - run:
+          name: clone bxextensions dependency
+          command: |
+            { # try
+                echo "Trying to clone identical branch name '$CIRCLE_BRANCH' from bxextensions."
+                git clone -b $CIRCLE_BRANCH --single-branch --depth=1 --recursive git@github.com:bloXroute-Labs/bxextensions-private.git bxextensions
+            } || { # catch
+                echo "Trying bxextensions master branch, could not find identical branch name '$CIRCLE_BRANCH'."
+                git clone -b master --single-branch --depth=1 --recursive git@github.com:bloXroute-Labs/bxextensions-private.git bxextensions
+            }
+            cd bxextensions
+            echo "$(git rev-parse HEAD)" > ~/ws/ext_tmp_file
       - run:
           name: install dependencies
           command: |
             sudo apt update &&
-            sudo apt install linux-headers-amd64
+            sudo apt install build-essential automake autogen autoconf libtool libtool-bin libssl-dev cmake linux-headers-amd64
       - run:
           name: install bxcommon
           command: |
@@ -60,59 +74,46 @@ jobs:
              cd bxcommon-internal
              bxcommonInternalBranch=$(git rev-parse --abbrev-ref HEAD)
              echo "Resolved branch $bxcommonInternalBranch for bxcommon-internal."
-      - run:
-          name: Install bxextensions dependency
-          command: |
-            { # try
-                echo "Trying to clone identical branch name '$CIRCLE_BRANCH' from bxextensions."
-                git clone -b $CIRCLE_BRANCH --single-branch --depth=1 --recursive git@github.com:bloXroute-Labs/bxextensions-private.git bxextensions
-            } || { # catch
-                echo "Trying bxextensions master branch, could not find identical branch name '$CIRCLE_BRANCH'."
-                git clone -b master --single-branch --depth=1 --recursive git@github.com:bloXroute-Labs/bxextensions-private.git bxextensions
-            }
+      - restore_cache: # restores saved dependency cache
+          key: bxextensions-{{ checksum "~/ws/ext_tmp_file" }}
+      - restore_cache: # restores saved dependency cache
+          key: bxgateway-{{ checksum "bxgateway/requirements.txt" }}-{{ checksum "bxgateway/requirements-dev.txt"}}-
+            {{ checksum "bxcommon/requirements.txt"}}-{{ checksum "bxcommon/requirements-dev.txt"}}-\
+            {{ checksum "bxcommon/requirements-optional.txt"}}
+          
       - run: # install and activate virtual environment with pip
           name: installing virtual env
           command: |
-            sudo rm -rf venv
-            python -m virtualenv venv
             . venv/bin/activate
-            pip install pip==19
-            pip install -r bxgateway/requirements.txt
-            pip install -r bxgateway/requirements-dev.txt
-            pip install -r bxcommon/requirements.txt
-            pip install -r bxcommon/requirements-dev.txt
-            pip install -r bxcommon/requirements-optional.txt
-      - persist_to_workspace:
-          root: .
-          paths:
-            - venv
-            - bxextensions
-            - bxcommon
-            - bxcommon-internal
-            - bxgateway
-  build_extensions:
-    executor: bloxroute-executor
-    working_directory: ~/ws
-    steps:
-      - attach_workspace:
-          at: ~/ws
+            pip install -r bxgateway/requirements.txt \
+              -r bxgateway/requirements-dev.txt \
+              -r bxcommon/requirements.txt \
+              -r bxcommon/requirements-dev.txt \
+              -r bxcommon/requirements-optional.txt
       - run:
-          name: install dependencies
           command: |
-            sudo apt install build-essential automake autogen autoconf libtool libtool-bin libssl-dev cmake
-      - run:
-          name: build extensions
-          command: |
+            . venv/bin/activate
             cd bxextensions
             python build_extensions.py
+      - save_cache: # special step to save dependency cache
+          key: bxextensions-{{ checksum "~/ws/ext_tmp_file" }}
+          paths:
+            - bxextensions
+      - save_cache: # special step to save dependency cache
+          key: bxgateway-{{ checksum "bxgateway/requirements.txt" }}-{{ checksum "bxgateway/requirements-dev.txt"}}-\
+            {{ checksum "bxcommon/requirements.txt"}}-{{ checksum "bxcommon/requirements-dev.txt"}}-\
+            {{ checksum "bxcommon/requirements-optional.txt"}}
+          paths:
+            - venv
+
       - persist_to_workspace:
           root: .
           paths:
             - venv
-            - bxextensions
             - bxcommon
             - bxcommon-internal
             - bxgateway
+            - bxextensions
   check:
     executor: bloxroute-executor
     working_directory: ~/ws
@@ -198,9 +199,9 @@ jobs:
           name: Initialize virtualenv
           command: |
             . venv/bin/activate
-            pip install -r bxrelay/requirements.txt
-            pip install -r bxrelay/requirements-dev.txt
-            pip install -r bxcommon/requirements-optional.txt
+            pip install -r bxrelay/requirements.txt \
+              -r bxrelay/requirements-dev.txt \
+              -r bxcommon/requirements-optional.txt
       - run:
           name: Integration Test
           command: |
@@ -212,9 +213,10 @@ jobs:
   build:
     working_directory: ~/ws
     docker:
-      - image: docker:17.05.0-ce-git
+      - image: docker:19.03.8
     steps:
-      - setup_remote_docker
+      - setup_remote_docker:
+          version: 19.03.8
       - attach_workspace:
           at: ~/ws
       - checkout:
@@ -224,7 +226,7 @@ jobs:
           name: Install dependencies
           command: |
             apk add --no-cache \
-              py-pip=9.0.0-r1
+              py-pip=18.1-r0 git
             pip install \
               docker-compose==1.12.0 \
               awscli==1.11.76
@@ -257,76 +259,24 @@ jobs:
           key: v1-{{ .Branch }}-{{ checksum "~/ws/bxgateway/requirements.txt" }}-{{ checksum "~/ws/bxcommon/requirements.txt" }}
           paths:
             - /caches/app.tar
-  publish:
-    working_directory: ~/ws
-    docker:
-      - image: docker:17.05.0-ce-git
-    steps:
-      - setup_remote_docker
-      - attach_workspace:
-          at: ~/ws
-      - checkout:
-          path:
-            "bxgateway"
-      - run:
-          name: Install dependencies
-          command: |
-            apk add --no-cache \
-              py-pip=9.0.0-r1
-            pip install \
-              docker-compose==1.12.0 \
-              awscli==1.11.76
-      - restore_cache:
-          keys:
-            - v1-{{ .Branch }}-{{ checksum "~/ws/bxgateway/requirements.txt" }}-{{ checksum "~/ws/bxcommon/requirements.txt" }}
-          paths:
-            - /caches/app.tar
-      - restore_cache:
-          keys:
-            - build-cache-{{ arch }}-{{ .Branch }}-{{ checksum "~/ws/bxextensions/release/MANIFEST.MF" }}
-      - run:
-          name: Load Docker image layer cache
-          command: |
-            set +o pipefail
-            docker load -i /caches/app.tar | true
-      - deploy:
-          name: Push application Docker image
-          command: |
-            aws configure set region us-east-1
-            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
-            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
-            $(aws ecr get-login)
-            docker tag app "${AWS_ECR_ENDPOINT}/bxgateway:${CIRCLE_BRANCH}"
-            docker push "${AWS_ECR_ENDPOINT}/bxgateway:${CIRCLE_BRANCH}"
-
 workflows:
   version: 2
 
   test-build:
     jobs:
       - initialize
-      - build_extensions:
-          requires:
-            - initialize
       - build:
           requires:
             - initialize
-      - check:
-          requires:
-            - build_extensions
-      - test:
-          requires:
-            - build_extensions
-      - e2e:
-          requires:
-            - build_extensions
-      - publish:
-          requires:
-            - build
-            - check
-            - test
-            - e2e
           filters:
             branches:
-              only:
-                develop
+              only: master
+      - check:
+          requires:
+            - initialize
+      - test:
+          requires:
+            - initialize
+      - e2e:
+          requires:
+            - initialize
