Bx286 sdn socket (#21)
Completes support for socket communication with relays (backwards support for rest and gateways)
Implements ping-pong keep-alive checks as-needed with relays
Implements SID updates over sockets
Implements peer updates over sockets
Includes refactor to send-ping variables for more clear meaning

* bx55 - move config to bxapi

* bx55 - refactor/simplifying startup params and api responsibilities

* bx55 - refactor peer configs

* bx55 - refactor main arg loading

* bx55 - refactor main arg loading

* bx55 - configuration restructure

* bx55 - relay and gateway config refactor stable

* bx55 - cleaning config redundancy

* bx55 - removing is_manager, added sharding

* bx-55 TX Message new implementation from blob message

* bx-55 commenting

* bx-187 bx-205 on connection timeout or error ask SDN for new best relay to connect to

* bx-187 bx-205 outbound peer fixes

* bx-221 new sid space

* bx-221 bx-235 redis persistence, async strategy, and permanent connections

* bx-221 adding python dependency

* bx-221 reformat/optimize imports

* bx-221 gateway txmessage test fix

* bx-221 cleaning up outbound peer retries with distinction for btc/non-btc

* bx-221 support for dynamic node registration

* bx55 separate host ip from external ip

* bx-221 sdn sockets connections

* bx55 moved config to support constant overrides

* bx55 refactor args

* bx235 args refactor

* bx286 broadcast filtering and ping-pong with sdn

* bx286 sdn peer updates for relays, rest-peer-updates for gateways

* bx286 sdn sid updates over sockets

* BX-269 refactored all hashing

* BX-269 basic encryption implemented

* BX-269 refactor to blockcache

* BX-269 add param to skip encryption

* BX-269 tdd

* BX-269 impl already has key scenario

* BX-269 added wait for key test

* BX-269 in progress cleanup commit

* BX-269 send keys as well

* BX-269 some structure for transmitting blocks

* BX-269 basic btc message parser tests

* BX-269 fix up btc node connection tests

* BX-269 fix up some test cases

* BX-269 fix test

* BX-269 style cleanup

* BX-269 fix up tests for btc blocks

* BX-269 fix up btc message endian ness test problems

* BX-269 added no encrypt test mode

* BX-269 handle duplicate messages better and send rawbytes

* BX-269 cleanup

* BX-269 cleanup

* BX-269 extra file

* BX-269 added gateway node integration test

* BX-269 add noencrypt test

* BX-269 PR comment: clarity

* BX-269 use bx hash where appropriate

* BX-269 PR: naming and tweaks

* BX-269 renaming encryptedblockcache to be payload agnostic

* BX-269 add test for ciphertext

* BX-269 renaming and error handling

* BX-269 create bloxroute cache

* BX-269 remove inner class

* BX-269 use shared constant

* BX-269 refactor message types and bloxroute encrypted cache

* BX-269 optimize / reformat imports

* BX-269 adding todo in code

* BX-269 drop hash if doesnt match

* BX-269 add decryption error wrapping and cache cleanup

* BX-269 fix cache construction

* BX-269 add note to talk with aleks

* BX-269 PR comments

* BX-269 PR: rename to sha256

* BX-269 PR: rename bx encrypted cache

* BX-269 add some shell scripts for easy bootup

* bx286 - PR Fixes

* BX-269 test fix and reformat

* BX-269 PR: rename subclass params

* BX-269 PR: renaming

* bx286 adding message factory support from @aspin

* bx286 refactor types -> type

* bx286 refactor types -> type

* bx286 test fixes

* bx286 test fixes

* bx286 message factory header fix, tx sid fix

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,7 +3,7 @@ version: 2.1
 executors:
   bloxroute-executor:
     docker:
-      - image: circleci/python:2.7
+    - image: circleci/python:2.7
     environment:
       PYTHONPATH: /home/circleci/ws/bxcommon/src:/home/circleci/ws/bxgateway/src
     working_directory: ~/ws
@@ -12,72 +12,72 @@ jobs:
   test:
     executor: bloxroute-executor
     steps:
-      - attach_workspace:
-          at: ~/ws
-      - checkout:
-          path:
-            "bxgateway"
-      - run:
-          name: Try to clone the corresponding bxcommon branch to this branch, or bxcommon/develop.
-          command: |
-            cd ~/ws/bxgateway
-            branchName=$(git rev-parse --abbrev-ref HEAD)
+    - attach_workspace:
+        at: ~/ws
+    - checkout:
+        path:
+          "bxgateway"
+    - run:
+        name: Try to clone the corresponding bxcommon branch to this branch, or bxcommon/develop.
+        command: |
+          cd ~/ws/bxgateway
+          branchName=$(git rev-parse --abbrev-ref HEAD)
 
-            cd ~/ws
-            { # try
-                echo "Trying to clone identical branch name '$branchName' from bxgateway."
-                git clone -b $branchName --single-branch --depth=1 git@github.com:bloXroute-Labs/bxcommon.git
-            } || { # catch
-                echo "Trying bxcommon develop branch, could not find identical branch name '$branchName' in bxgateway."
-                git clone -b develop --single-branch --depth=1 git@github.com:bloXroute-Labs/bxcommon.git
-            }
-            cd bxcommon
-            bxcommonBranch=$(git rev-parse --abbrev-ref HEAD)
-            echo "Resolved branch $bxcommonBranch for bxcommon."
-      - restore_cache: # restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run
-          key: deps1-{{ .Branch }}-{{ checksum "bxgateway/requirements.txt" }}
-      - run: # install and activate virtual environment with pip
-          command: |
-            python -m virtualenv venv
-            . venv/bin/activate
-            pip install -r bxgateway/requirements.txt
-            pip install -r bxcommon/requirements.txt
-      - save_cache: # special step to save dependency cache
-          key: deps1-{{ .Branch }}-{{ checksum "bxgateway/requirements.txt" }}
-          paths:
-            - "venv"
-      - persist_to_workspace:
-          root: .
-          paths:
-            - venv
-      - run: # run tests
-          name: Unit Tests
-          command: |
-            . venv/bin/activate
-            cd bxgateway/test/unit
-            python -m unittest discover --verbose
-      - run: # check coverage
-          name: Check Coverage
-          command: |
-            . venv/bin/activate
-            cd bxgateway/test/unit
-            coverage run --source=/home/circleci/ws/bxgateway/src -m unittest discover && coverage report --fail-under=01
-      - run: # run tests
-          name: Integration Tests
-          command: |
-            . venv/bin/activate
-            cd bxgateway/test/integration
-            python -m unittest discover --verbose
-      - run: # run pylint
-          name: Lint Score
-          command: |
-            . venv/bin/activate
-            cd bxgateway
-            # The || exit 0 bypasses not failing the build for <10 score
-            PYTHONPATH=../bxcommon/src/ pylint src/bxgateway --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" --rcfile=../bxcommon/pylintrc || exit 0
-      - store_artifacts:
-          path: test-reports/
-          destination: tr1
+          cd ~/ws
+          { # try
+              echo "Trying to clone identical branch name '$branchName' from bxgateway."
+              git clone -b $branchName --single-branch --depth=1 git@github.com:bloXroute-Labs/bxcommon.git
+          } || { # catch
+              echo "Trying bxcommon develop branch, could not find identical branch name '$branchName' in bxgateway."
+              git clone -b develop --single-branch --depth=1 git@github.com:bloXroute-Labs/bxcommon.git
+          }
+          cd bxcommon
+          bxcommonBranch=$(git rev-parse --abbrev-ref HEAD)
+          echo "Resolved branch $bxcommonBranch for bxcommon."
+    - restore_cache: # restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run
+        key: deps1-{{ .Branch }}-{{ checksum "bxgateway/requirements.txt" }}
+    - run: # install and activate virtual environment with pip
+        command: |
+          python -m virtualenv venv
+          . venv/bin/activate
+          pip install -r bxgateway/requirements.txt
+          pip install -r bxcommon/requirements.txt
+    - save_cache: # special step to save dependency cache
+        key: deps1-{{ .Branch }}-{{ checksum "bxgateway/requirements.txt" }}
+        paths:
+        - "venv"
+    - persist_to_workspace:
+        root: .
+        paths:
+        - venv
+    - run: # run tests
+        name: Unit Tests
+        command: |
+          . venv/bin/activate
+          cd bxgateway/test/unit
+          python -m unittest discover --verbose
+    - run: # check coverage
+        name: Check Coverage
+        command: |
+          . venv/bin/activate
+          cd bxgateway/test/unit
+          coverage run --source=/home/circleci/ws/bxgateway/src -m unittest discover && coverage report --fail-under=01
+    - run: # run tests
+        name: Integration Tests
+        command: |
+          . venv/bin/activate
+          cd bxgateway/test/integration
+          python -m unittest discover --verbose
+    - run: # run pylint
+        name: Lint Score
+        command: |
+          . venv/bin/activate
+          cd bxgateway
+          # The || exit 0 bypasses not failing the build for <10 score
+          PYTHONPATH=../bxcommon/src/ pylint src/bxgateway --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" --rcfile=../bxcommon/pylintrc || exit 0
+    - store_artifacts:
+        path: test-reports/
+        destination: tr1
 
   e2e:
     executor: bloxroute-executor
@@ -129,47 +129,47 @@ jobs:
             python -m unittest discover --verbose
   build:
     docker:
-      - image: circleci/python:2.7
+    - image: circleci/python:2.7
     working_directory: ~/ws
 
     steps:
-      - checkout
-      - attach_workspace:
-          at: ~/ws
-      - run:
-          name: Package
-          command: 'echo "Yay build!"'
+    - checkout
+    - attach_workspace:
+        at: ~/ws
+    - run:
+        name: Package
+        command: 'echo "Yay build!"'
 
   deploy:
     docker:
-      - image: circleci/python:2.7
+    - image: circleci/python:2.7
     working_directory: ~/ws
 
     steps:
-      - checkout
-      - attach_workspace:
-          at: ~/ws
-      - run:
-          name: Package
-          command: 'echo "Yay deploy!"'
+    - checkout
+    - attach_workspace:
+        at: ~/ws
+    - run:
+        name: Package
+        command: 'echo "Yay deploy!"'
 
 workflows:
   version: 2
 
   test-build:
     jobs:
-      - test
-      - e2e
-      - build:
-          requires:
-            - test
-          filters:
-            branches:
-              only: develop
+    - test
+    - e2e
+    - build:
+        requires:
+        - test
+        filters:
+          branches:
+            only: develop
 
-      - deploy:
-          filters:
-            branches:
-              only: develop
-          requires:
-            - build
+    - deploy:
+        filters:
+          branches:
+            only: develop
+        requires:
+        - build
