Updated imports to use models/node_type from bxcommon (#398)
* Updated imports to use models/node_type from bxcommon

* Added bxcommon-internal to circle, pyre config, Docker files

* Fixed format issue in circleci file

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -6,7 +6,7 @@ executors:
     # TODO: Use AWS repository or create bloXroute account on Docker Hub
     - image: circleci/python:3.7
     environment:
-      PYTHONPATH: /home/circleci/ws/bxcommon/src:/home/circleci/ws/bxgateway/src:/home/circleci/ws/bxextensions
+      PYTHONPATH: /home/circleci/ws/bxcommon/src:/home/circleci/ws/bxgateway/src:/home/circleci/ws/bxextensions:/home/circleci/ws/bxcommon-internal/src/
     working_directory: ~/ws
 
 jobs:
@@ -48,6 +48,23 @@ jobs:
              bxcommonBranch=$(git rev-parse --abbrev-ref HEAD)
              echo "Resolved branch $bxcommonBranch for bxcommon."
       - run:
+          name: install bxcommon-internal
+          command: |
+             cd ~/ws/bxgateway
+             branchName=$(git rev-parse --abbrev-ref HEAD)
+
+             cd ~/ws
+             { # try
+                 echo "Trying to clone identical branch name '$branchName' from bxcommon-internal."
+                 git clone -b $branchName --single-branch --depth=1 git@github.com:bloXroute-Labs/bxcommon-internal.git bxcommon-internal
+             } || { # catch
+                 echo "Trying bxcommon-internal develop branch, could not find identical branch name '$branchName'"
+                 git clone -b develop --single-branch --depth=1 git@github.com:bloXroute-Labs/bxcommon-internal.git bxcommon-internal
+             }
+             cd bxcommon-internal
+             bxcommonInternalBranch=$(git rev-parse --abbrev-ref HEAD)
+             echo "Resolved branch $bxcommonInternalBranch for bxcommon-internal."
+      - run:
           name: Install bxextensions dependency
           command: |
             { # try
@@ -72,6 +89,7 @@ jobs:
             - venv
             - bxextensions
             - bxcommon
+            - bxcommon-internal
             - bxgateway
   build_extensions:
     executor: bloxroute-executor
@@ -95,6 +113,7 @@ jobs:
             - venv
             - bxextensions
             - bxcommon
+            - bxcommon-internal
             - bxgateway
   check:
     executor: bloxroute-executor
